[build]
buildCommand = "npm install"

[deploy]
command="node index.js"

[cron]
schedule = "0 */4 * * 1-5"
command="node index.js"

[env]
MONDAY_API_KEY=eyJhbGciOiJIUzI1NiJ9.eyJ0aWQiOjM5NTYxNjUyMCwiYWFpIjoxMSwidWlkIjo2NDYyOTU2NywiaWFkIjoiMjAyNC0wOC0xMVQyMDoxMTozNS4wMDBaIiwicGVyIjoibWU6d3JpdGUiLCJhY3RpZCI6MjQ4Njk4MTQsInJnbiI6InVzZTEifQ.Iap1bvEBzDN-dQOVs3L5NpUUgqvQMYbqduLX4lT-0J8
MONDAY_BOARD_ID=7203682412
MAILGUN_API_KEY=9a836622d1268b7be109c1047623c101-a26b1841-ac82a94d
MAILGUN_DOMAIN=sandboxf56e73b0680241428a37fcab880455e0.mailgun.org